### ISSUE TITLE
[1.20.1 - 2.1.2] Uncraftable potions can appear in fishtraps that dont use bait

### ISSUE THREAD

**Issue by Looxond** [Uraneptus/Fishermens-Trap#18]
![image](https://github.com/Uraneptus/Fishermens-Trap/assets/29359853/fcb355bd-5dc5-485e-83c3-daa0698e24d0)

In this instance im playing in my full modpack but testing it on an empty instance without FD or any other mod outside JEI still reveals uncraftable potions as a possible loot

**Comment by Uraneptus** [comment]
Hi thanks for opening this, however it is not really a bug.
That's just displayed in JEI, the Fishtrap won't actually fish an uncraftable potion. The loot table that is used when no bait is present includes a random potion, however JEI can't easily read the possible outcome of a loot table thus I had to put all possible items into a tag. JEI then displays the content of that tag, but because of the way potions and tags are coded I cannot add potions with a specific effect to the tag, which causes JEI to display an Uncraftable Potions. 

I'm aware that this solution is not ideal and I hope I can find a better way at some point to handle this, but for now we have to live with this sadly :/
